swagger: '2.0'
info:
  title: "API OBMEP DATA DRIVEN"
  description: "API para consumo do Frontend, com os dados dos últimos cinco anos da OBMEP"
  version: 1.0

paths:
  /api/listar-escolas:
    get:
      tags:
        - 'Lista todas as Escolas que participaram das olimpíadas'
      summary: 'Lista todas as Escolas que participaram das olimpíadas'
      responses:
        200:
          description: OK
          schema:
            type: string
